/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStockOutRouteImport } from './routes/_app/stock-out'
import { Route as AppStockInRouteImport } from './routes/_app/stock-in'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStockOutRoute = AppStockOutRouteImport.update({
  id: '/stock-out',
  path: '/stock-out',
  getParentRoute: () => AppRoute,
} as any)
const AppStockInRoute = AppStockInRouteImport.update({
  id: '/stock-in',
  path: '/stock-in',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/import': typeof AppImportRoute
  '/inventory': typeof AppInventoryRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/stock-in': typeof AppStockInRoute
  '/stock-out': typeof AppStockOutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/import': typeof AppImportRoute
  '/inventory': typeof AppInventoryRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/stock-in': typeof AppStockInRoute
  '/stock-out': typeof AppStockOutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/import': typeof AppImportRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stock-in': typeof AppStockInRoute
  '/_app/stock-out': typeof AppStockOutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/dashboard'
    | '/import'
    | '/inventory'
    | '/profile'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock-in'
    | '/stock-out'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/dashboard'
    | '/import'
    | '/inventory'
    | '/profile'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock-in'
    | '/stock-out'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/alerts'
    | '/_app/dashboard'
    | '/_app/import'
    | '/_app/inventory'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/stock-in'
    | '/_app/stock-out'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/stock-out': {
      id: '/_app/stock-out'
      path: '/stock-out'
      fullPath: '/stock-out'
      preLoaderRoute: typeof AppStockOutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock-in': {
      id: '/_app/stock-in'
      path: '/stock-in'
      fullPath: '/stock-in'
      preLoaderRoute: typeof AppStockInRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppImportRoute: typeof AppImportRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStockInRoute: typeof AppStockInRoute
  AppStockOutRoute: typeof AppStockOutRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppImportRoute: AppImportRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStockInRoute: AppStockInRoute,
  AppStockOutRoute: AppStockOutRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
